### ISSUE TITLE
Checonf

### ISSUE THREAD

**Issue by TylerJewell** [wernight/kubernetes-che#1]
Hi - we haven't announced it yet, but we'll be hosting a checonf in a few weeks as a virtual conference.  One of the sessions is running che on openshift.  Maybe we want to cover the kubernetes configuration as an alternative as well?  See the 1pm speaking slot.

https://www.eclipse.org/che/checonf/sessions.html

**Comment by wernight** [comment]
Sounds interesting. I'd have to check to allocate a time slot and double check a few things but sounds definitely possible. I've sent you en e-mail to share contacts.

**Comment by wernight** [comment]
I'll close this issue; keep me updated via IM/e-mail/...
